AM.UI.WEBB/Models/ErrorViewModel.cs
namespace AM.UI.WEBB.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AM.UI.WEBB/Controllers/HomeController.cs
using System.Diagnostics;
using AM.UI.WEBB.Models;
using Microsoft.AspNetCore.Mvc;

namespace AM.UI.WEBB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AM.UI.WEBB/Controllers/InfirmierController.cs
using AM.ApplicationCore.Domain;
using AM.ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AM.UI.WEBB.Controllers
{
    public class InfirmierController : Controller
    {
        IServiceInfirmier si;
        IServiceLaboratoire sl;
    
        public InfirmierController(IServiceInfirmier si, IServiceLaboratoire sl)
        {
            this.si = si;
            this.sl = sl;
        }

        // GET: InfirmierController
        public ActionResult Index()
        {
            return View(si.GetMany());
        }
        // GET: Infirmier/Patient/5
        public ActionResult Patient(int id)
        {
            var infirmier = si.GetById(id);
            if (infirmier == null)
            {
                return NotFound();
            }

            // Toujours retourner une liste, même si Bilans est null
            var patients = (infirmier.Bilans ?? new List<Bilan>())
                .Select(b => b.Patient)
                .Where(p => p != null)
                .Distinct()
                .ToList();

            return View(patients);
        }



        // GET: InfirmierController/Details/5
        public ActionResult Details(int id)
        {   
            return View(si.GetById(id));
        }

        // GET: InfirmierController/Create
        public ActionResult Create()
        {
            ViewBag.lsLabo = new SelectList(sl.GetMany(), "LaboratoireId", "Intitule");
            return View();
        }

        // POST: InfirmierController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Infirmier collection)
        {
            try
            {
                si.Add(collection);
                si.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: InfirmierController/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.lsLabo = new SelectList(sl.GetMany(), "LaboratoireId", "Intitule");

            return View(si.GetById(id));
        }

        // POST: InfirmierController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Infirmier collection)
        {
            try
            {
                si.Update(collection);
                si.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: InfirmierController/Delete/5
        public ActionResult Delete(int id)
        {    
            return View(si.GetById(id));
        }

        // POST: InfirmierController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Infirmier collection)
        {
            try
            {
                si.Delete(si.GetById(id));
                si.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AM.UI.WEBB/Controllers/PatientController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AM.UI.WEBB.Controllers
{
    public class PatientController : Controller
    {
        // GET: PatientController
        public ActionResult Index()
        {
            return View();
        }

        // GET: PatientController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PatientController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PatientController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PatientController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PatientController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PatientController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PatientController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AM.UI.WEBB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AM.UI.WEBB/Views/Infirmier/Create.cshtml
@model AM.ApplicationCore.Domain.Infirmier

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Infirmier</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        
            <div class="form-group">
                <label asp-for="NomComplet" class="control-label"></label>
                <input asp-for="NomComplet" class="form-control" />
                <span asp-validation-for="NomComplet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Specialite" class="control-label"></label>
                <select asp-for="Specialite" class="form-control" asp-items="@Html.GetEnumSelectList<AM.ApplicationCore.Domain.specialite>()" ></select>
                <span asp-validation-for="Specialite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LaboratoireFK" class="control-label"></label>
                <select asp-items="ViewBag.lsLabo" asp-for="LaboratoireFK" class="form-control"></select>
                <span asp-validation-for="LaboratoireFK" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AM.UI.WEBB/Views/Infirmier/Delete.cshtml
@model AM.ApplicationCore.Domain.Infirmier

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Infirmier</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InfirmierId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InfirmierId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomComplet)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomComplet)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Specialite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Specialite)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LaboratoireFK)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LaboratoireFK)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AM.UI.WEBB/Views/Infirmier/Details.cshtml
@model AM.ApplicationCore.Domain.Infirmier

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Infirmier</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InfirmierId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InfirmierId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomComplet)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomComplet)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Specialite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Specialite)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LaboratoireFK)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LaboratoireFK)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

AM.UI.WEBB/Views/Infirmier/Edit.cshtml
@model AM.ApplicationCore.Domain.Infirmier

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Infirmier</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
      
            <div class="form-group">
                <label asp-for="NomComplet" class="control-label"></label>
                <input asp-for="NomComplet" class="form-control" />
                <span asp-validation-for="NomComplet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Specialite" class="control-label"></label>
                <select asp-for="Specialite" class="form-control" asp-items="@Html.GetEnumSelectList<AM.ApplicationCore.Domain.specialite>()"></select>
                <span asp-validation-for="Specialite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LaboratoireFK" class="control-label"></label>
                <select asp-items="ViewBag.lsLabo" asp-for="LaboratoireFK" class="form-control"></select>
                <span asp-validation-for="LaboratoireFK" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AM.UI.WEBB/Views/Infirmier/Index.cshtml
@model IEnumerable<AM.ApplicationCore.Domain.Infirmier>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.InfirmierId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NomComplet)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Specialite)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LaboratoireFK)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.InfirmierId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NomComplet)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Specialite)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LaboratoireFK)
            </td>
            <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.InfirmierId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.InfirmierId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.InfirmierId })  |
                    <a asp-area="" asp-controller="Infirmier" asp-action="Patient" asp-route-id="@item.InfirmierId">Patient</a>
            </td>
        </tr>
}
    </tbody>
</table>

AM.UI.WEBB/Views/Infirmier/Patient.cshtml
@model IEnumerable<AM.ApplicationCore.Domain.Patient>

@{
    ViewData["Title"] = "Patient";
}

<h1>Patient</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CodePatient)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailPatient)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Informations)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NomComplet)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeroTel)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CodePatient)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailPatient)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Informations)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NomComplet)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroTel)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

AM.UI.WEBB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AM.UI.WEBB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AM.UI.WEBB.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AM.UI.WEBB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - AM.UI.WEBB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>